// Runs axe-core + pa11y against every page in dist/html.
// Serves dist/html over a short-lived HTTP server so both tools can reach it.
// Usage: node scripts/a11y.mjs  (via npm run a11y)
//
// Install note: pa11y pulls in puppeteer which tries to download Chrome.
// To skip that download (e.g. on CI or this macOS host with system Chrome),
// run:  PUPPETEER_SKIP_DOWNLOAD=true npm install
// (or install with .puppeteerrc.cjs present, which sets skipDownload:true)
// The script auto-detects Google Chrome.app on macOS and sets
// PUPPETEER_EXECUTABLE_PATH so pa11y and axe can find it.
// On CI (Linux) either install a Chromium package or set PUPPETEER_EXECUTABLE_PATH.

import { readdirSync, existsSync } from "node:fs";
import { spawn, spawnSync } from "node:child_process";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const DIST = join(ROOT, "dist", "html");
const PORT = 8123;

// Locate CLI binaries installed in node_modules/.bin (avoids npx --no-install issues).
const BIN = join(ROOT, "node_modules", ".bin");
const AXE_BIN = join(BIN, "axe");
const PA11Y_BIN = join(BIN, "pa11y");

// Auto-detect system Chrome on macOS when Puppeteer's bundled browser was skipped.
const MACOS_CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
if (!process.env.PUPPETEER_EXECUTABLE_PATH && existsSync(MACOS_CHROME)) {
  process.env.PUPPETEER_EXECUTABLE_PATH = MACOS_CHROME;
  console.log(`[a11y] Using system Chrome: ${MACOS_CHROME}`);
}

if (!existsSync(AXE_BIN)) {
  console.error(`[a11y] axe binary not found at ${AXE_BIN}. Run: PUPPETEER_SKIP_DOWNLOAD=true npm install`);
  process.exit(1);
}
if (!existsSync(PA11Y_BIN)) {
  console.error(`[a11y] pa11y binary not found at ${PA11Y_BIN}. Run: PUPPETEER_SKIP_DOWNLOAD=true npm install`);
  process.exit(1);
}

// Start local HTTP server over dist/html.
const server = spawn(
  "python3",
  ["-m", "http.server", String(PORT), "--directory", DIST],
  { stdio: "inherit" }
);
process.on("exit", () => server.kill());

// Give the server a moment to bind.
await new Promise((r) => setTimeout(r, 800));

const pages = readdirSync(DIST)
  .filter((f) => f.endsWith(".html") && f !== "index.html")
  .sort();

let failed = 0;

// ── axe-core disabled rules ────────────────────────────────────────────────
//
// region: Paged.js (loaded as a deferred polyfill for screen preview) restructures
//   the DOM at runtime, wrapping all content in:
//     .pagedjs_pages > .pagedjs_page > .pagedjs_sheet > .pagedjs_page_content
//   This is outside the authored landmark tree and triggers axe's "region" rule
//   as a false positive. The authored HTML has proper landmark structure (<main>,
//   role="banner", role="contentinfo") and the print output is generated by
//   WeasyPrint (not Paged.js), so this rule is inapplicable here.
//
// landmark-no-duplicate-main, landmark-unique: Paged.js splits content-heavy
//   pages (those that overflow one A4 sheet) across multiple ".pagedjs_page"
//   nodes, cloning the authored <main id="main-content"> into each sheet. This
//   makes axe see multiple <main> elements with the same id. Again a Paged.js
//   runtime DOM artefact — the authored HTML has exactly one <main>.
//
// landmark-no-duplicate-contentinfo: Same as above — Paged.js clones the
//   <footer role="contentinfo"> into each pagination sheet. The authored HTML
//   has exactly one footer per page.
//
const AXE_DISABLED = [
  "region",
  "landmark-no-duplicate-main",
  "landmark-unique",
  "landmark-no-duplicate-contentinfo",
];

// ── pa11y ignored rules ───────────────────────────────────────────────────
//
// WCAG2AA.Principle3.Guideline3_2.3_2_2.H32.2 (form without submit button):
//   The DOC-* pages are printable paper forms. They use <form novalidate> as
//   a structural container for labelled inputs, but they are never submitted
//   digitally — users print, fill with pen, and submit physically. A submit
//   button would be misleading and non-functional on a printed form.
//   This rule is genuinely inapplicable for print-form HTML.
//
// WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.Fieldset.Name
// WCAG2AA.Principle1.Guideline1_3.1_3_1.H71.NoLegend
//   Paged.js splits multi-page form content across multiple ".pagedjs_page"
//   nodes. When a <fieldset> overflows one page, Paged.js clones the fieldset
//   element into the continuation page using data-split-from/data-split-to
//   attributes, but the cloned fieldset does not include the original <legend>.
//   Pa11y sees this Paged.js-generated fragment and flags it. The authored HTML
//   has exactly one <fieldset> with one <legend>; the split is a runtime
//   pagination artefact.
//
const PA11Y_IGNORE = [
  "WCAG2AA.Principle3.Guideline3_2.3_2_2.H32.2",
  "WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.Fieldset.Name",
  "WCAG2AA.Principle1.Guideline1_3.1_3_1.H71.NoLegend",
];

for (const page of pages) {
  const url = `http://localhost:${PORT}/${page}`;
  console.log(`\n== ${page} ==`);

  // axe-core CLI — exits non-zero on violations.
  // --disable takes a comma-separated list of rule IDs.
  const axeArgs = [url, "--disable", AXE_DISABLED.join(","), "--exit"];
  const axe = spawnSync(AXE_BIN, axeArgs, { stdio: "inherit" });
  if (axe.status !== 0) failed++;

  // pa11y — WCAG 2.1 AA standard, exits non-zero on violations.
  const pa11yArgs = ["--standard", "WCAG2AA"];
  for (const code of PA11Y_IGNORE) pa11yArgs.push("--ignore", code);
  pa11yArgs.push(url);
  const pa11y = spawnSync(PA11Y_BIN, pa11yArgs, { stdio: "inherit" });
  if (pa11y.status !== 0) failed++;
}

server.kill();

if (failed > 0) {
  console.error(`\n${failed} accessibility check(s) failed`);
  process.exit(1);
}
console.log("\nAll pages passed axe + pa11y");
